name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]
        mongodb-version: ['4.0', '4.2', '4.4', '5.0']
    name: Node ${{ matrix.node }} MongoDB ${{ matrix.mongodb-version }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install

    - run: npm test

  eslint:
    runs-on: ubuntu-latest
    name: Evaluate eslint
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install

      - run: npm run eslint
