name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]
        mongodb-version: ['5.0', '6.0', '7.0']
    name: Node ${{ matrix.node }} MongoDB ${{ matrix.mongodb-version }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: yarn --frozen-lockfile

    - run: yarn test

  lint:
    runs-on: ubuntu-latest
    name: Evaluate eslint
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn --frozen-lockfile

      - run: yarn lint
